### PR TITLE
Update honeycomb.md

### PR DESCRIPTION
**Pull request by jonathan-m-hamilton**
Minor syntax cleanup and proposed two additional initial committers.

### CODE REVIEW

**Comment by tkuhrt** [comment]
@jonathan-m-hamilton : Can you amend your commit to include the `-s` option? This will be required when we do a PR into Hyperledger Labs. See steps 9 and 10 in [this Gist](https://gist.github.com/tkuhrt/10211ae0a26a91a8c030d00344f7d11b).

**Comment by jonathan-m-hamilton** [comment]
@tkuhrt thanks for the guidance, I believe I was able to amend correctly  Let me know if anything else missing. I will make sure to sign from the start from now on!

**Comment by tkuhrt** [comment]
Looks like the original commit is still there -- the one without the signoff.

**Comment by tkuhrt** [comment]
I pulled in your changes manually.

**Comment by jonathan-m-hamilton** [comment]
Thank you!!

**Pull request closed without merging**
